language: shell

# build newer version of libcurl with support for 3FS_CURLOPT_KEEP_SENDING_ON_ERROR and CURLOPT_SSL_ENABLE_ALPN
# [WAN] curl.cpp:ResetHandle(1855): The CURLOPT_SSL_ENABLE_ALPN option could not be unset. S3 server does not support ALPN, then this option should be disabled to maximize performance. you need to use libcurl 7.36.0 or later.
# [WAN] curl.cpp:ResetHandle(1858): The S3FS_CURLOPT_KEEP_SENDING_ON_ERROR option could not be set. For maximize performance you need to enable this option and you should use libcurl 7.51.0 or later.

before_install:
- sudo apt-get install -y libxml2-dev libfuse-dev fuse 
- wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz
- tar -xzf openssl-1.1.1c.tar.gz
- cd openssl-1.1.1c
- ./config no-weak-ssl-ciphers no-ssl2 no-ssl3 no-comp
- make >/dev/null || make 
- sudo make install >/dev/null 
- sudo ldconfig 
- cd ..
- wget https://github.com/nghttp2/nghttp2/releases/download/v1.39.1/nghttp2-1.39.1.tar.bz2
- tar -xjf nghttp2-1.39.1.tar.bz2
- cd nghttp2-1.39.1
- ./configure 
- make && sudo make install
- sudo ldconfig
- cd ..
- wget https://curl.haxx.se/download/curl-7.65.1.tar.bz2
- tar -xjf curl-7.65.1.tar.bz2
- cd curl-7.65.1
- ./configure --with-ca-path=/etc/ssl/certs --with-nghttp2
- make && sudo make install && sudo ldconfig 
- cd ..

# openssl make/install is super verbose and known to work
# redirected stdout bc full output is too much for travis and has to be viewed as raw log
# these packages were replaced by building curl/openssl from source: libcurl4-openssl-dev libssl-dev 

script: "./build-bundle.sh"
# only build on the 'test' branch or on tags
branches:
  only:
  - /^v[0-9]/
  - test

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: yfKNUJsBa0rbPoeHid4AHvBQ2jKPdN/A4OTJ+BUf3+OsjtVEha2lZi5lOalYaxTPKcNcsms4IsYY1sIhSawzbQHR3I2YJDLiYY297XIMkU73kXu3je3WwEY6viOIdCXhev/2CebyXxV6/I2TpOge6sDrXexIzlc6W/Ca3tCIgTHCX1NNaB+N/4lRxhr9qbjiNZYjbMLjm1osN6TnmVetJ9GvzpndlTi9ROt1owzFzySNFeRDlmFQhXUmQr1UcQ1jtMP3fJgQg5WhSC3anB7D+9f3T4FE9hBUwZDOS0KtZlIFpgPzAegGUldtyJKkM7yLWR++q+9GoiKiLhwGCh+7Lux6JyzGnwMP0PFlM7Rt7zyhgmGajMMIblKEFLRt/WjmU6tTtejqAATTdHDYhHDoh6YtKFO33GjOXW1nodVoiMSvUjqzbKNqUoLvGuvHjcUTXmAZ8DslubvSgfIZ0F15k8sy0DtVziX5zoQlI4IZDNA704AJ371BkvkN+9KgoZey0aXoJAtsi9Pmz18tfCQUrDBAAf2hSe2uG8UMwIEcyAfO4NJGCrBJ6tvACWRAndMnKzY91Z3F+TQgFy1jdPG+yf7OG6F/gaH2txscEz1Jhy57qXQX+qpRP5j2hXaibx7FuhGWCqUuy29jadQkx6qAGngdalW8xwxm37HJ8TFyTkM=
    file: osiris-bundle.tgz
    on:
      repo: MI-OSiRIS/osiris-bundle
      tags: true
  # create draft release from test branch
  - provider: releases
    skip_cleanup: true
    draft: true
    api_key:
      secure: yfKNUJsBa0rbPoeHid4AHvBQ2jKPdN/A4OTJ+BUf3+OsjtVEha2lZi5lOalYaxTPKcNcsms4IsYY1sIhSawzbQHR3I2YJDLiYY297XIMkU73kXu3je3WwEY6viOIdCXhev/2CebyXxV6/I2TpOge6sDrXexIzlc6W/Ca3tCIgTHCX1NNaB+N/4lRxhr9qbjiNZYjbMLjm1osN6TnmVetJ9GvzpndlTi9ROt1owzFzySNFeRDlmFQhXUmQr1UcQ1jtMP3fJgQg5WhSC3anB7D+9f3T4FE9hBUwZDOS0KtZlIFpgPzAegGUldtyJKkM7yLWR++q+9GoiKiLhwGCh+7Lux6JyzGnwMP0PFlM7Rt7zyhgmGajMMIblKEFLRt/WjmU6tTtejqAATTdHDYhHDoh6YtKFO33GjOXW1nodVoiMSvUjqzbKNqUoLvGuvHjcUTXmAZ8DslubvSgfIZ0F15k8sy0DtVziX5zoQlI4IZDNA704AJ371BkvkN+9KgoZey0aXoJAtsi9Pmz18tfCQUrDBAAf2hSe2uG8UMwIEcyAfO4NJGCrBJ6tvACWRAndMnKzY91Z3F+TQgFy1jdPG+yf7OG6F/gaH2txscEz1Jhy57qXQX+qpRP5j2hXaibx7FuhGWCqUuy29jadQkx6qAGngdalW8xwxm37HJ8TFyTkM=
    file: osiris-bundle.tgz
    on:
      repo: MI-OSiRIS/osiris-bundle
      branch: test
      tags: false

